# Generated by Django 3.0.8 on 2020-08-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='wirter',
            new_name='c_wirter',
        ),
    ]
