# Generated by Django 3.0.8 on 2020-08-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200813_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='c_writer',
            new_name='writer',
        ),
    ]
